language: python
python:
  - "3.4"
env:
  - BERKELEYDB_DIR=/usr
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdb5.1 libdb5.1-dev
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
    nosetests --with-coverage --cover-package=pmpi
after_success:
  coveralls
